Algoritmo "algoritmo"

Var

nome, sobrenome, turma: caractere
idade, ano: inteiro

Inicio

escreval("FICHA DE ALUNO: DIGITE OS DADOS ABAIXO")
escreva("Seu nome: ")
leia(nome)
escreva("Seu sobrenome: ")
leia(sobrenome)
escreva("Sua idade: ")
leia(idade)
escreva("Seu ano da escola: ")
leia(ano)
escreva("Sua turma: ")
leia(turma)

escreval("")
escreval("DADOS INSERIDOS:")
escreval("Nome: ", nome, " ", sobrenome)
escreval("Sua idade: ", idade)
escreval("Sua turma: ", ano, "-", turma)

Fimalgoritmo