Algoritmo "operadores"
Var
d, s : real

Inicio
//Crie um programa que leia o número de dias trabalhados em um mês
//e mostre o salário de um funcionário,
//sabendo que ele trabalha 8 horas por dia e ganha R$25 por hora trabalhada.

escreva("Qual número de dias trabalhados no mês?: ")
leia(d)
s <- (d * 8) * 25.0
escreval("")
escreval("Trabalhando ", d," dias, e considerando um período de 8 horas trabalhadas, sendo R$ 25,00 a hora, seu salário será ", s)
Fimalgoritmo