/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thiago.cadastro;

import javax.swing.JOptionPane;

/**
 *
 * @author t.baiense
 */
public class ConexaoBD extends javax.swing.JFrame {

    /**
     * Creates new form ConexaoBD
     */
    public ConexaoBD() {
        initComponents();
        jbtn_oculto.setVisible(false);
        jlbl_desconectado.setVisible(false);
        jlbl_conectado.setVisible(false);
        jlbl_outro.setVisible(false);
         jlbl_selecionado.setVisible(false);
        jlbl_radio.setVisible(false);
        jlbl_checkbox.setVisible(false);
        jcmb_itens.addItem("teste de insercao");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jlbl_conectado = new javax.swing.JLabel();
        jlbl_desconectado = new javax.swing.JLabel();
        jlbl_outro = new javax.swing.JLabel();
        jbtn_visivel = new javax.swing.JButton();
        jbtn_oculto = new javax.swing.JButton();
        jlbl_selecionado = new javax.swing.JLabel();
        jlbl_checkbox = new javax.swing.JLabel();
        jlbl_radio = new javax.swing.JLabel();
        jbtn_botao = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jcmb_itens = new javax.swing.JComboBox<>();
        jlbl_info = new javax.swing.JLabel();
        jtxtf_id = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_conectado.setText("Conectado");
        getContentPane().add(jlbl_conectado, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 32, -1, -1));

        jlbl_desconectado.setText("Desconectado");
        getContentPane().add(jlbl_desconectado, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 54, -1, -1));

        jlbl_outro.setText("ACHOUUUUUU!!");
        getContentPane().add(jlbl_outro, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 88, -1, -1));

        jbtn_visivel.setText("Visivel");
        jbtn_visivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_visivelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_visivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 130, -1, -1));

        jbtn_oculto.setText("Oculto");
        jbtn_oculto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ocultoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_oculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 130, -1, -1));

        jlbl_selecionado.setText("Selecionado");
        getContentPane().add(jlbl_selecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jlbl_checkbox.setText("Checkbox");
        getContentPane().add(jlbl_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jlbl_radio.setText("Radio");
        getContentPane().add(jlbl_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jbtn_botao.setText("Botão");
        jbtn_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_botaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jcmb_itens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmb_itens, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 190, -1));

        jlbl_info.setText("Informação");
        getContentPane().add(jlbl_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jtxtf_id.setMinimumSize(new java.awt.Dimension(100, 26));
        getContentPane().add(jtxtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, -1));

        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_visivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_visivelActionPerformed
        jlbl_outro.setVisible(true);
        jlbl_conectado.setVisible(true);
        jlbl_desconectado.setVisible(false);
        jbtn_oculto.setVisible(true);
    }//GEN-LAST:event_jbtn_visivelActionPerformed

    private void jbtn_ocultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ocultoActionPerformed
        jlbl_outro.setVisible(false);
        jlbl_conectado.setVisible(false);
        jlbl_desconectado.setVisible(true);
    }//GEN-LAST:event_jbtn_ocultoActionPerformed

    private void jbtn_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_botaoActionPerformed
        jlbl_selecionado.setVisible(true);
        jlbl_radio.setVisible(true);
        jlbl_checkbox.setVisible(true);
        
        jlbl_selecionado.setText("Item selecionado: " + (String) jcmb_itens.getSelectedItem());
        jlbl_radio.setText("Radio valor: " + String.valueOf(jRadioButton1.isSelected()));
        jlbl_checkbox.setText("Checkbox valor: " + String.valueOf(jCheckBox1.isSelected()));
    }//GEN-LAST:event_jbtn_botaoActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        int id;
        try {
            id = Integer.parseInt(jtxtf_id.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "valor inválido para id");
            return;
        }
        Cliente cliente = Receber.cliente(id);
        
        if (cliente == null) {
            jlbl_info.setText("Cliente não encontrado");
        } else {
            jlbl_info.setText(cliente.nome);
        }
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexaoBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton jbtn_botao;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_oculto;
    private javax.swing.JButton jbtn_visivel;
    private javax.swing.JComboBox<String> jcmb_itens;
    private javax.swing.JLabel jlbl_checkbox;
    private javax.swing.JLabel jlbl_conectado;
    private javax.swing.JLabel jlbl_desconectado;
    private javax.swing.JLabel jlbl_info;
    private javax.swing.JLabel jlbl_outro;
    private javax.swing.JLabel jlbl_radio;
    private javax.swing.JLabel jlbl_selecionado;
    private javax.swing.JTextField jtxtf_id;
    // End of variables declaration//GEN-END:variables
}
