/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thiago.cadastro;

import javax.swing.JOptionPane;

/**
 *
 * @author t.baiense
 */
public class JFrame_DeleteCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_DeleteCliente
     */
    public JFrame_DeleteCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_nome = new javax.swing.JLabel();
        jlbl_telefone = new javax.swing.JLabel();
        jtxtf_telefone = new javax.swing.JTextField();
        jtxtf_nome = new javax.swing.JTextField();
        jbtn_deletar = new javax.swing.JButton();
        jcmb_sexo = new javax.swing.JComboBox<>();
        jlbl_sexo = new javax.swing.JLabel();
        jlbl_nome1 = new javax.swing.JLabel();
        jtxtf_id = new javax.swing.JTextField();
        jbtn_receber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_nome.setText("Nome");
        jPanel1.add(jlbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jlbl_telefone.setText("Telefone");
        jPanel1.add(jlbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 50, -1));

        jtxtf_telefone.setToolTipText("");
        jtxtf_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_telefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtf_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 218, -1));

        jtxtf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_nomeActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 218, -1));

        jbtn_deletar.setText("Deletar");
        jbtn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_deletarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 110, 30));

        jcmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(jcmb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 220, -1));

        jlbl_sexo.setText("Sexo");
        jPanel1.add(jlbl_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jlbl_nome1.setText("ID");
        jPanel1.add(jlbl_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jtxtf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_idActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 218, -1));

        jbtn_receber.setText("Receber");
        jbtn_receber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_receberActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_receber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtf_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_telefoneActionPerformed

    private void jtxtf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_nomeActionPerformed

    private void jbtn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_deletarActionPerformed
        try {
            int id = Integer.parseInt(jtxtf_id.getText());
            String nome, sexo, telefone;
            
            nome = jtxtf_nome.getText().trim();
            sexo = (String)jcmb_sexo.getSelectedItem();
            telefone = jtxtf_telefone.getText().trim();
            
            Cliente cliente = new Cliente(nome, sexo, telefone);
            cliente.setId(id);
            
            Deletar.cliente(cliente);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Formato de id inválido!");
        }
        
        
        
    }//GEN-LAST:event_jbtn_deletarActionPerformed

    private void jtxtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_idActionPerformed

    private void jbtn_receberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_receberActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jtxtf_id.getText());
        Cliente cl = Receber.cliente(id);
        jtxtf_id.setText(String.valueOf(cl.getId()));
        jtxtf_nome.setText(cl.nome);
        int index = (cl.sexo.equals("M") ? 0 : 1);
        jcmb_sexo.setSelectedIndex(index);
        jcmb_sexo.repaint();
        jtxtf_telefone.setText(cl.telefone);
        System.out.print(index);
    }//GEN-LAST:event_jbtn_receberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_DeleteCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_deletar;
    private javax.swing.JButton jbtn_receber;
    private javax.swing.JComboBox<String> jcmb_sexo;
    private javax.swing.JLabel jlbl_nome;
    private javax.swing.JLabel jlbl_nome1;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JLabel jlbl_telefone;
    private javax.swing.JTextField jtxtf_id;
    private javax.swing.JTextField jtxtf_nome;
    private javax.swing.JTextField jtxtf_telefone;
    // End of variables declaration//GEN-END:variables
}
