package thiago.cadastro;

import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author t.baiense
 */
public class JFrame_CadastroCliente extends javax.swing.JFrame {
    
    String nome, telefone;
    String sexo;
    
    
    /**
     * Creates new form JFrame_CadastroCliente
     */
    public JFrame_CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_nome = new javax.swing.JLabel();
        jlbl_telefone = new javax.swing.JLabel();
        jtxtf_telefone = new javax.swing.JTextField();
        jtxtf_nome = new javax.swing.JTextField();
        jbtn_enviar = new javax.swing.JButton();
        jlbl_log = new javax.swing.JLabel();
        jlbl_estado = new javax.swing.JLabel();
        jcmb_sexo = new javax.swing.JComboBox<>();
        jlbl_sexo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_nome.setText("Nome");
        jPanel1.add(jlbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jlbl_telefone.setText("Telefone");
        jPanel1.add(jlbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 50, -1));

        jtxtf_telefone.setToolTipText("");
        jtxtf_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_telefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtf_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 218, -1));

        jtxtf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_nomeActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 218, -1));

        jbtn_enviar.setText("Enviar");
        jbtn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enviarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 110, 30));

        jlbl_log.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_log.setText("Aguardando envio...");
        jPanel1.add(jlbl_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, -1));

        jlbl_estado.setText("Estado:");
        jPanel1.add(jlbl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jcmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(jcmb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 220, -1));

        jlbl_sexo.setText("Sexo");
        jPanel1.add(jlbl_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtf_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_telefoneActionPerformed

    private void jtxtf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_nomeActionPerformed

    private void jbtn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enviarActionPerformed
        nome = jtxtf_nome.getText().trim();
        sexo = ((String)jcmb_sexo.getSelectedItem()).trim().substring(0, 1);
        telefone = jtxtf_telefone.getText().trim();
        jlbl_log.setText("Recebido dados!");
        
        Cadastro.cliente(nome, sexo, telefone);
        Cliente cl = Receber.lastCliente();
        JOptionPane.showMessageDialog(null, String.format("""
                                                          ID do cliente: %d
                                                          Nome informado: %s
                                                          Sexo informado: %s
                                                          Telefone informado: %s
                                                          """, cl.getId(), cl.nome, cl.sexo, cl.telefone));
    }//GEN-LAST:event_jbtn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_enviar;
    private javax.swing.JComboBox<String> jcmb_sexo;
    private javax.swing.JLabel jlbl_estado;
    private javax.swing.JLabel jlbl_log;
    private javax.swing.JLabel jlbl_nome;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JLabel jlbl_telefone;
    private javax.swing.JTextField jtxtf_nome;
    private javax.swing.JTextField jtxtf_telefone;
    // End of variables declaration//GEN-END:variables
}
