/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thiago.cadastro;

/**
 *
 * @author t.baiense
 */
public class JFrame_CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_CadastroProduto
     */
    public JFrame_CadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtf_codigo = new javax.swing.JTextField();
        jtxtf_categoria = new javax.swing.JTextField();
        jtxtf_estoque = new javax.swing.JTextField();
        jtxtf_preco_custo = new javax.swing.JTextField();
        jtxtf_dt_validade = new javax.swing.JTextField();
        jtxtf_caracteristica = new javax.swing.JTextField();
        jtxtf_nome = new javax.swing.JTextField();
        jtxtf_descricao = new javax.swing.JTextField();
        jtxt_categoria = new javax.swing.JTextField();
        jtxtf_preco_venda = new javax.swing.JTextField();
        jtxtf_unidade_peso = new javax.swing.JTextField();
        jtxtf_peso = new javax.swing.JTextField();
        jtxtf_unidade = new javax.swing.JTextField();
        jtxtf_fornecedor = new javax.swing.JTextField();
        jtxtf_fabricante = new javax.swing.JTextField();
        jtxtf_dt_fabricacao = new javax.swing.JTextField();
        jtxtf_rua = new javax.swing.JTextField();
        jtxtf_cidade = new javax.swing.JTextField();
        jtxtf_estado = new javax.swing.JTextField();
        jtxtf_pais = new javax.swing.JTextField();
        jbtn_enviar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jtxtf_usuario_autor = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Categoria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Unidade");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel5.setText("Preco Custo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setText("Preco Venda");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel7.setText("Fornecedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel8.setText("Peso");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel9.setText("Unidade Peso");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel10.setText("Fabricante");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel11.setText("Data de fabricação");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel12.setText("Rua");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel13.setText("Data de validade");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel14.setText("Cidade");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel15.setText("Estado");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel16.setText("Pais");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        jLabel17.setText("Descricao");
        jLabel17.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel17ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel18.setText("Código");
        jLabel18.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel18ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel19.setText("Estoque");
        jLabel19.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel19ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel20.setText("Caracteristicas");
        jLabel20.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel20ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel21.setText("Estado");
        jLabel21.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel21ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 40, -1));
        jPanel1.add(jtxtf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 140, -1));
        jPanel1.add(jtxtf_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 140, -1));
        jPanel1.add(jtxtf_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 140, -1));
        jPanel1.add(jtxtf_preco_custo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, -1));
        jPanel1.add(jtxtf_dt_validade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 140, -1));
        jPanel1.add(jtxtf_caracteristica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 140, -1));
        jPanel1.add(jtxtf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 140, -1));
        jPanel1.add(jtxtf_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, -1));
        jPanel1.add(jtxt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, -1));
        jPanel1.add(jtxtf_preco_venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 140, -1));
        jPanel1.add(jtxtf_unidade_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 140, -1));
        jPanel1.add(jtxtf_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, -1));
        jPanel1.add(jtxtf_unidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 140, -1));
        jPanel1.add(jtxtf_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 140, -1));
        jPanel1.add(jtxtf_fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 140, -1));
        jPanel1.add(jtxtf_dt_fabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 140, -1));
        jPanel1.add(jtxtf_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 140, -1));
        jPanel1.add(jtxtf_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 140, -1));
        jPanel1.add(jtxtf_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 140, -1));
        jPanel1.add(jtxtf_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 140, -1));

        jbtn_enviar.setText("Enviar");
        jbtn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enviarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, -1));

        jLabel22.setText("Usuario Autor");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));
        jPanel1.add(jtxtf_usuario_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel17ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17ComponentHidden

    private void jLabel18ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel18ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18ComponentHidden

    private void jLabel19ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel19ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19ComponentHidden

    private void jLabel20ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel20ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20ComponentHidden

    private void jLabel21ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel21ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21ComponentHidden

    private void jbtn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_enviar;
    private javax.swing.JTextField jtxt_categoria;
    private javax.swing.JTextField jtxtf_caracteristica;
    private javax.swing.JTextField jtxtf_categoria;
    private javax.swing.JTextField jtxtf_cidade;
    private javax.swing.JTextField jtxtf_codigo;
    private javax.swing.JTextField jtxtf_descricao;
    private javax.swing.JTextField jtxtf_dt_fabricacao;
    private javax.swing.JTextField jtxtf_dt_validade;
    private javax.swing.JTextField jtxtf_estado;
    private javax.swing.JTextField jtxtf_estoque;
    private javax.swing.JTextField jtxtf_fabricante;
    private javax.swing.JTextField jtxtf_fornecedor;
    private javax.swing.JTextField jtxtf_nome;
    private javax.swing.JTextField jtxtf_pais;
    private javax.swing.JTextField jtxtf_peso;
    private javax.swing.JTextField jtxtf_preco_custo;
    private javax.swing.JTextField jtxtf_preco_venda;
    private javax.swing.JTextField jtxtf_rua;
    private javax.swing.JTextField jtxtf_unidade;
    private javax.swing.JTextField jtxtf_unidade_peso;
    private javax.swing.JTextField jtxtf_usuario_autor;
    // End of variables declaration//GEN-END:variables
}
