CREATE DATABASE ESCOLA_SENAI;
USE ESCOLA_SENAI;
CREATE TABLE TB_ALUNO(
	RA_ALUN INT NOT NULL AUTO_INCREMENT,
    NOME_ALU VARCHAR(40),
    DT_NASC_ALU DATETIME DEFAULT CURRENT_TIMESTAMP,
    CPF_ALU CHAR(11),
    SEXO_ALU CHAR(1),
    PRIMARY KEY (RA_ALUN)
);
CREATE TABLE TB_CURSO (
	COD_ALU INT NOT NULL AUTO_INCREMENT,
    RA_ALU INT NOT NULL,
    DATA_MAT DATE,
    COD_CURS INT NOT NULL,
    PRIMARY KEY (COD_ALU),
    FOREIGN KEY (RA_ALU) REFERENCES TB_ALUNO(RA_ALU),
    FOREIGN KEY (COD_CURS) REFERENCES TB_MATRICULA(COD_CURS)
);
CREATE TABLE TB_MATRICULA (
	COD_CURS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_CURS VARCHAR(40) NOT NULL,
    PER_CURS INT,
    DUR_CURS INT,
    VALOR_CURS DECIMAL(7,2)
);